import type { Recommendation, SearchResponse } from "./types";

const repositories: Recommendation[] = [
  {
    rank: 1,
    full_name: "fastapi/fastapi",
    description: "FastAPI framework, high performance, easy to learn, fast to code, ready for production.",
    html_url: "https://github.com/fastapi/fastapi",
    score: 96.4,
    stars: 93600,
    language: "Python",
    license_spdx: "MIT",
    pushed_at: "2026-08-02T08:45:00Z",
    constraint_match: { language: "MATCH", archived: "MATCH", license: "MATCH", activity: "MATCH" },
    score_breakdown: { relevance: 35, activity: 28.7, popularity: 14.9, metadata: 10, license: 10 },
    reasons: ["FastAPI 技术栈强匹配", "最近 24 小时有推送", "许可证为 MIT"],
    risks: ["项目规模较大，首次贡献需先从文档 Issue 开始", "尚未验证本地 Windows 启动成本"],
  },
  {
    rank: 2,
    full_name: "uriyyo/fastapi-pagination",
    description: "FastAPI pagination library with support for SQLAlchemy, Tortoise ORM and more.",
    html_url: "https://github.com/uriyyo/fastapi-pagination",
    score: 91.8,
    stars: 6100,
    language: "Python",
    license_spdx: "MIT",
    pushed_at: "2026-07-30T16:20:00Z",
    constraint_match: { language: "MATCH", archived: "MATCH", license: "MATCH", activity: "MATCH" },
    score_breakdown: { relevance: 35, activity: 27.8, popularity: 11.4, metadata: 10, license: 10 },
    reasons: ["项目边界清晰，适合阅读完整实现", "测试与类型体系信号良好", "近期持续维护"],
    risks: ["需要理解 ORM 适配层", "贡献指南证据待深度调查"],
  },
  {
    rank: 3,
    full_name: "laurentS/slowapi",
    description: "A rate limiter for Starlette and FastAPI, inspired by Flask-Limiter.",
    html_url: "https://github.com/laurentS/slowapi",
    score: 87.2,
    stars: 2600,
    language: "Python",
    license_spdx: "MIT",
    pushed_at: "2026-07-18T10:10:00Z",
    constraint_match: { language: "MATCH", archived: "MATCH", license: "MATCH", activity: "MATCH" },
    score_breakdown: { relevance: 33, activity: 25.2, popularity: 10.2, metadata: 10, license: 10 },
    reasons: ["代码规模适中", "FastAPI 周边组件语义匹配", "许可证满足约束"],
    risks: ["维护者响应样本较少", "开放 Issue 数量有限"],
  },
  {
    rank: 4,
    full_name: "zhanymkanov/fastapi-best-practices",
    description: "FastAPI best practices and conventions used in production applications.",
    html_url: "https://github.com/zhanymkanov/fastapi-best-practices",
    score: 84.6,
    stars: 13200,
    language: "Python",
    license_spdx: "MIT",
    pushed_at: "2026-06-28T09:30:00Z",
    constraint_match: { language: "MATCH", archived: "MATCH", license: "MATCH", activity: "MATCH" },
    score_breakdown: { relevance: 35, activity: 21.9, popularity: 12.4, metadata: 7.5, license: 10 },
    reasons: ["学习目的高度匹配", "包含生产实践主题", "近期仍有内容更新"],
    risks: ["更偏知识库而非完整应用", "不一定提供可贡献的代码型 Issue"],
  },
];

export const demoResponse: SearchResponse = {
  query: "找一个适合 Python 初学者学习 FastAPI 的项目，MIT 许可证，最近半年有更新",
  generated_github_query: "FastAPI language:Python archived:false pushed:>2026-02-01",
  constraints: {
    language: "Python",
    technologies: ["FastAPI"],
    licenses: ["MIT"],
    exclude_archived: true,
    pushed_after: "2026-02-01",
  },
  source_total_count: 130908,
  eligible_candidate_count: 83,
  ranking_version: "metadata-baseline-v1",
  results: repositories,
};
